### ISSUE TITLE
Improve GraphViz support for MS Windows

### ISSUE THREAD

**Issue by clue** [clue/graph-composer#17]
https://github.com/clue/graph/pull/99

**Comment by jatubio** [comment]
Hi, i'm trying to get working on windows but i get only a picture with a box with `__root` word. And word ausgabe on command prompt

**Comment by clue** [comment]
> Hi, i'm trying to get working on windows but i get only a picture with a box with __root word. And word ausgabe on command prompt

Indeed, windows support is somewhat limited at the moment – any input (PR anybody?) is welcome, I suppose :)

This ticket is actually a duplicate of #14, so I'm closing this in favor of the other one (this is not a bug – it's a missing feature).
