### ISSUE TITLE
Does not work after 'composer global require clue/graph-composer'

### ISSUE THREAD

**Issue by tomasliubinas** [clue/graph-composer#21]
When installed over `composer global require clue/graph-composer` after trying to to run `graph-composer` it says:
ERROR: Composer not properly set up! Run "composer install" or see README.md for more details

**Comment by clue** [comment]
Thanks for posting this and reminding me of tagging a new release! :)

This is already documented in #16: until a new tag has been pushed, you need to target the `*@dev` version (which is anything but ideal for obvious reasons).
