### ISSUE TITLE
composer install doesn't work

### ISSUE THREAD

**Issue by MECU** [clue/graph-composer#28]
Ran this to install:

`composer require --dev clue/graph-composer`

Tried this but there is no vendor/bin folder even:
`./vendor/bin/graph-composer show`

Tried this but get error message:
`./vendor/clue/graph-composer/bin/graph-composer show`

```
sh: dot: command not found

  [Fhaculty\Graph\Exception\UnexpectedValueException]
  Unable to invoke "dot" to create image file (code 127)
```

Need to update installation directions to require dot even if installing via composer.
Also fix or update installation directions for the vendor/bin problem.

**Comment by angelxmoreno** [comment]
this is old. why has this not been addressed? 
@MECU so the solution is installing `dot` ?

**Comment by angelxmoreno** [comment]
whoops, i do see it:
`Additionally, you'll have to install GraphViz (dot executable)`

**Comment by angelxmoreno** [comment]
I ran `brew install graphviz` on OSX and all things work. Of course, You need brew installed first.

**Comment by clue** [comment]
Does anybody feel like filing a PR that makes the installation docs more obvious? :+1: 

(This also refs #4 which suggests we add a warning if the `dot` executable can not be found)

**Comment by clue** [comment]
Thank you for reporting! I'm currently working on improving the installation instructions via #4 and will release a new version soon-ish :shipit:
