### ISSUE TITLE
Release 1.0.0 is missing version

### ISSUE THREAD

**Issue by mishak87** [clue/graph-composer#29]
``` sh
wget https://github.com/clue/graph-composer/releases/download/v1.0.0/graph-composer.phar
php graph-composer.phar --version
```

Output:

```
graph-composer version @git_tag@
```

Expected:

```
graph-composer version 1.0.0
```

**Comment by clue** [comment]
Thanks for spotting, this should not have slipped in :)

This refs https://github.com/clue/phar-composer/issues/39, I'll see what we can do about this in the next release :+1:
