### ISSUE TITLE
Update symfony/console

### ISSUE THREAD

**Issue by keradus** [clue/graph-composer#30]
Please update symfony console dependency:
"symfony/console": "^2.1|^3.0",

**Comment by clue** [comment]
PRs welcome :+1:

**Comment by keradus** [comment]
#31

**Comment by pelmered** [comment]
This should be reopened. I would like V4.0 support as well.

**Comment by clue** [comment]
@pelmered The original request has been fulfilled, PRs to add support for v4 are welcome :+1:
