### ISSUE TITLE
What about only draw the dependencies of a sub package in a project?

### ISSUE THREAD

**Issue by yarcowang** [clue/graph-composer#37]
Ex.:
```
graph-composer . --package clue/graph-composer
```
If current project has several dependencies

**Comment by clue** [comment]
@yarcowang Thank you for reporting!

Can you elaborate on the use case for this? It sounds like this may be related to #33 or #11?

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:
