### ISSUE TITLE
Unable to invoke "dot" to create image file (code 127)

### ISSUE THREAD

**Issue by elementallos** [clue/graph-composer#72]
I get this error:
```bash
Unable to invoke "dot" to create image file (code 127)
```

I have installed the graphviz, I have tried to reinstall it again, but I still get the same error.

Using Yii2, controller action:
```php
public function actionGraph()
{
    $dir = Yii::getAlias('@app') . '/vendor';
    $graphComposer = new \Clue\GraphComposer\Graph\GraphComposer($dir);
    $graph = $graphComposer->createGraph();

    $graphviz = new \Graphp\GraphViz\GraphViz();
    $graphviz->setFormat('svg');
    $svg = $graphviz->createImageFile($graph);
    return $this->render('graph', ['svg' => $svg]);
}
```
and view:
```php
<?php

/**
 * @var $this yii\web\View
 * @var $svg string
 */

var_dump($svg);
use yii\helpers\Html;

$this->title = 'Dependency Graph';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="site-dependency-graph">
    <h1><?= Html::encode($this->title) ?></h1><br />

    <div id="graph-placeholder">
        <!-- place here the svg file -->
        <?= $svg ?>
    </div>
</div>
```

**Comment by SimonFrings** [comment]
Hey @elementallos, thanks for bringing this up :+1:

Like @clue described in https://github.com/graphp/graphviz/issues/31, the `Unable to invoke "dot" to create image file (code 127)...` error message means you do not have GraphViz installed (the `dot` executable is part of the GraphViz package). On Debian/Ubuntu-based system you may simply install it like this:

```bash
$ sudo apt install graphviz
```

This has  been answered in https://github.com/clue/graph-composer/issues/4 as well and is also mentioned inside the documentation.
Ref: https://github.com/clue/graph-composer/pull/43

I believe this should answer your question, so I will close this ticket for now. We can reopen this if you encounter the same issues again after trying out the solutions mentioned in here.

**Comment by elementallos** [comment]
But is not working anyway for me...

**Comment by SimonFrings** [comment]
> As I said already, in the first message, I have already tried to do:
> ```bash
> $ sudo apt install graphviz
> ```

You're right, so this would mean you can't even try `dot -v` to check the GraphViz version, right?

**Comment by elementallos** [comment]
Yes, I can do `dot -v`, it is only on the PHP code, when I try to generate the .svg
The installation with `sudo apt install` is successful: I don't get any error messages. But when I try to use the command, it looks like this (var_dump):
```
'dot' -T 'svg' '/tmp/graphvizDEdKjJ' -o '/tmp/graphvizDEdKjJ.svg'
```

**Comment by sardjn** [comment]
@SimonFrings any updates?

**Comment by SimonFrings** [comment]
> […] But when I try to use the command, it looks like this (var_dump):

@sardjn You're trying to access some temporary files that are created and also removed by the project itself, this is why the message tells you that dot can't open `/tmp/graphvizDEdKjJ` (the file doesn't exist). It seems like you have graphviz successfully installed, otherwise the message would tell you that it doesn't know the dot command, you just can't access these unknown files.
